### PR TITLE
Migrate l10n_fi_business_code 14 -> 15

### PR DESCRIPTION
**Pull request by aisopuro**
Changes are in last 2 commits.

Ping #47

### CODE REVIEW

**Comment by aisopuro** [comment]
Sorry for the pinging, but can @jarmokortetjarvi and @mlaitinen help me get this reviewed and merged? We'd love to have it fast if possible. Let me know if I can help get it done.

**Review by mlaitinen — APPROVED** [review]
LGTM.

Are you planning to migrate `l10n_fi_business_code_validate` as well?

**Comment by aisopuro** [comment]
> LGTM.
> 
> Are you planning to migrate `l10n_fi_business_code_validate` as well?

Alas, probably not now. It is not one of our direct dependencies, and we don't have extra time to spare unfortunately.

**Pull request merged**
