### PR TITLE
[MIG] l10n_fi_banks to 11.0

### PR DESCRIPTION
**Pull request by aisopuro**
Should be merged after https://github.com/OCA/l10n-finland/pull/22

### CODE REVIEW

**Review by mlaitinen — APPROVED** [review]
LGTM. Wasn't sure about the empty translation template and Finnish translation files, but I guess having them won't hurt anyone.

**Comment by jarmokortetjarvi** [comment]
:+1: 
The translation files are unnecessary, yes, but I don't feel like removing them would be necessary here

**Review by jarmokortetjarvi — APPROVED** [review]

**Review by mlaitinen — CHANGES_REQUESTED** [review]
`2018-10-05 11:05:04,001 150 WARNING openerp_test odoo.models: res.bank.create() includes unknown fields: fax`
You should remove the `fax` fields.

**Comment by aisopuro** [comment]
Fax fields removed @mlaitinen

**Review by mlaitinen — APPROVED** [review]

**Pull request merged**
