### PR TITLE
[14.0] dotfiles update needs manual intervention

### PR DESCRIPTION
**Pull request by aisopuro**
Replaces #56 as I cannot push the fix to that branch directly.

### CODE REVIEW

**Comment by etobella** [comment]
Can you change travis for Github actions? You just need to do copier update and select github :smile:

**Comment by aisopuro** [comment]
I ran `copier update`, and answered the questions to the best of my ability. It seems to have updated a fair bit more than just the test runner: https://github.com/OCA/l10n-finland/pull/57/commits/a8058c365c054f009337d0082477c884f8047096

In fact it seems to have re-introduced several things that the original @OCA-git-bot removed: https://github.com/OCA/l10n-finland/pull/57/commits/14c98a61dedaa30d1a1a6508c1f59b5963d68ffe

I'll see if I can fix the code coverage, but can you @etobella tell me if these differences are OK? It seems like I've given different answers to `copier update` than @OCA-git-bot did, and I just want to make sure I'm not configuring anything wrong.

**Comment by etobella** [comment]
You did it greatly :smile:

**Review by etobella — APPROVED** [review]
/ocabot merge patch

**Pull request closed without merging**
