### PR TITLE
[MIG] 15.0 l10n_fi_sale_refund_payment_reference

### PR DESCRIPTION
**Pull request by nedaszilinskas**
Migration from 13.0

### CODE REVIEW

**Comment by nedaszilinskas** [comment]
Request for the review :) Ping @aisopuro @mlaitinen @OCA/community-maintainers.

Now that in the 15.0 branch this module doesn't exist I had to manually copy it from 13.0, which loses all migration diff. and is a little less than ideal. Do you have any advice/recommendations/ref. to the manual on how to avoid that?

**Comment by dreispt** [comment]
Yes. Please see #47 , it explains the process needed to keep the module commit history.

**Comment by mlaitinen** [comment]
In particular this section: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch

**Comment by nedaszilinskas** [comment]
Thank you, @dreispt @mlaitinen! I must have been blind to miss that before 🤦 I've pushed the update.

**Review by mlaitinen — APPROVED** [review]
LGTM

**Comment by anikeenko-viktor** [comment]
@mlaitinen Since that was approved, could you please merge it?

**Comment by mlaitinen** [comment]
> @mlaitinen Since that was approved, could you please merge it?

I'd wait for @aisopuro's approval before merging

**Review by aisopuro — APPROVED** [review]
LGTM

**Pull request merged**
