### PR TITLE
[ADD] Also compute payment references for refunds

### PR DESCRIPTION
**Pull request by aisopuro**

### CODE REVIEW

**Comment by jarmokortetjarvi** [comment]
This looks fine to me.

Build errors seem to be related to formatting or other simple issues that pre-commit should be able to fix.

**Comment by aisopuro** [comment]
Thanks for the heads up @jarmokortetjarvi . GitHub apparently didn't notify me the build had failed, so I wouldn't have noticed otherwise :sweat_smile: 

I'll fix this... soonish is the best I can promise.

**Comment by aisopuro** [comment]
Alright, finally green. Still needs one approval, can @mlaitinen provide that?

**Review by mlaitinen — APPROVED** [review]
:+1:

**Review by jarmokortetjarvi — APPROVED** [review]

**Pull request merged**
