### PR TITLE
[MIG] l10n_fi_business_code and l10n_fi_business_code_validate

### PR DESCRIPTION
**Pull request by aisopuro**

### CODE REVIEW

**Review by mlaitinen — COMMENTED** [review]
I think I found a bug in the validation. If I set 2349368-9 (incorrect Finnish ID) as the business ID for a Taiwanese company and save, I don't get any error (I shouldn't get any error). When I change the country to Finland, I still don't get any error and I think that I should get an error. It seems to trigger the validation only when I alter the business code.

2349368-8 is a valid business code and I had to set that as the business code, save, change the business code back to 2349368-9 and save to get the error message.

**Comment by aisopuro** [comment]
I think that bug belongs in https://github.com/OCA/partner-contact/tree/11.0/partner_identification @mlaitinen . This module only provides the logic for validation: it does not control when validation happens. I agree that it seems like changing the country should trigger validation, but the actual constraint is defined separately, and only triggers on changes to fields on the `res.partner.id_number` record itself: https://github.com/OCA/partner-contact/blob/11.0/partner_identification/models/res_partner_id_number.py#L18.

The implementation of this whole thing isn't exactly standard. It might be because OCA doesn't think that this is a failure situation, but who knows.

**Comment by mlaitinen** [comment]
I don't think it belongs to the `partner_identification` module because this is a custom identification field that we have created. `partner_identification` couldn't possibly know when to trigger the validation, so I think we need to do it in this module.

I think we should have our own constraint that validates all of the identifiers connected to the partner if the country is changed.

**Comment by aisopuro** [comment]
But the whole point of the `partner_identification` module is to provide a unified base on which to build these kinds of country-specific code validations. It seems to me that if it doesn't provide a mechanism for checking something when a partner's country is changed, that's a bug in the base functionality.

**Comment by mlaitinen** [comment]
Fair point.

**Review by mlaitinen — APPROVED** [review]

**Comment by aisopuro** [comment]
Ping @jarmokortetjarvi would it be possible to have this reviewed/accepted?

**Comment by jarmokortetjarvi** [comment]
> Ping @jarmokortetjarvi would it be possible to have this reviewed/accepted?

Just rebuilt the runbot and reviewing :)

**Review by jarmokortetjarvi — APPROVED** [review]
Looks fine to me.

Verified this:
> I think I found a bug in the validation. If I set 2349368-9 (incorrect Finnish ID) as the business ID for a Taiwanese company and save, I don't get any error (I shouldn't get any error). When I change the country to Finland, I still don't get any error and I think that I should get an error. It seems to trigger the validation only when I alter the business code.

But agree that this bug should be raised as a separate issue, as it doesn't really concern the migration (the logic is flawed in earlier version too). I also wasn't able to find a field-dependency functionality in `partner_identification`

**Pull request merged**
